{% set name = "safe_yaml" %}
{% set version = "1.0.5" %}
{% set hash = "a6ac2d64b7eb027bdeeca1851fe7e7af0d668e133e8a88066a0c6f7087d9f848" %}
{% set build = 2 %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: {{ hash }}

build:
  noarch: generic
  number: {{ build }}
  script:
    - gem install --norc -l -V --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem

requirements:
  host:
    - ruby
  run:
    - {{ pin_compatible('ruby', max_pin='x.x') }}

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE.txt
  summary: Parse YAML safely

  doc_url: http://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/dtao/{{ name }}

extra:
  recipe-maintainers:
    - sodre
    - jdmarques
